### PR TITLE
Add snapshots module

### PR DESCRIPTION
**Pull request by ikem-krueger**
I wanted to use xbian-config to manage the btrfs snapshots. Hence I wrote a module for it.

The usage is fairly simple:

**GUI:**

"Snapshots - Manage snapshots" -> "Snapshot - Create snapshot of a volume" -> select volume
"Snapshots - Manage snapshots" -> "Rollback - Rollback to a snapshot of a volume" -> select volume -> select snapshot

**CMD:**

```bash
# list volumes
xbian-config snapshots listvol

# create snapshot for volume
xbian-config snapshots snapshot <volume>

# list snapshots for volume
xbian-config snapshots list <volume>

# rollback to snapshot
xbian-config snapshots rollback <volume> <snapshot>
```

I want you to review it, and if it fits, merge it.

Feedback is welcome.

### CODE REVIEW

**Comment by mkreisl** [comment]
Sounds interesting, thanks. But why did you do this based on **xbian-config-bash**, which has not been used since 2014.
Currently **xbian-package-config-shell** is used only, which also contains the xbian-config CLI.

Here the PR is therefore unfortunately pointless

**Comment by ikem-krueger** [comment]
I didn‘t know that **xbian-package-config-shell** was the right package. I will take a look at it, and try again.

What‘s the purpose of **xbian-config-bash**?

**Comment by mkreisl** [comment]
`dpkg -S $(which xbian-config)` tells you from where that xbian-config cames from

> What‘s the purpose of **xbian-config-bash**?

I don't know anything about that. I guess it was just a transitional repository and then integrated into xbian-package-config-shell. In any case, it has not been used since 2014.

I'm sorry that you have to do some of the work twice now

**Comment by ikem-krueger** [comment]
I made the necessary changes in **xbian-package-config-shell**.

I will close that pull request and delete the fork.

**Comment by mkreisl** [comment]
Already seen. that was fast. I'll watch it tonight

**Pull request closed without merging**
