### PR TITLE
Added danish language files

### PR DESCRIPTION
**Pull request by muddermanden**
Several danish language files added for modules.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you remove the .DS_Store file from the request?

**Comment by CurlyMoo** [comment]
And i also miss the additions to the `functions/language` file.

**Comment by CurlyMoo** [comment]
And as far as i know, the country code for denmark is `DK` instead of `DA` (http://www.realifewebdesigns.com/web-marketing/abbreviations-countries.asp)

**Comment by muddermanden** [comment]
> Can you remove the .DS_Store file from the request?

Yes, I will remove that file. It slipped through since it was late at night.

> And i also miss the additions to the functions/language file

I thought I should add that one when all the language files were created, which I will do now and then add the changes to `functions/language`.

> And as far as i know, the country code for denmark is DK instead of DA (http://www.realifewebdesigns.com/web-marketing/abbreviations-countries.asp)

You are right that the country code for Denmark is DK, but since this is the language I used the language code DA (http://www.mcanerin.com/EN/articles/meta-language.asp). Some countries have more than one language, which is why I would recommend the use of language codes instead of country codes. Anyway, I can change it if you want me to.

**Comment by CurlyMoo** [comment]
Just use DK...

Awaiting the rest.

**Comment by muddermanden** [comment]
I have created all the language files now, added Danish to `functions/language`, etc. Do I need to take any further action now?

**Comment by CurlyMoo** [comment]
Nope, thanks!

**Comment by CurlyMoo** [comment]
Can you also translate these new 2 lines for me (and rename the variables accordingly) asap: https://github.com/xbianonpi/xbian-config-bash/blob/master/modules/xbmc/lang/en#L22-L25

**Pull request merged**
